services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: quicknotesdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d quicknotesdb -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - quicknotes
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

networks:
  quicknotes:

volumes:
  pg_data:
